### ISSUE TITLE
Incorrect graph for last question on quiz

### ISSUE THREAD

**Issue by MagicMilly** [learn-co-curriculum/dsc-1-02-16-measures-of-dispersion-quiz#1]
The last question of the quiz asks for a histogram of the data, but the solution for the quiz shows a boxplot.

**Comment by PeterBell** [comment]
Thanks for catching! Just fixed with https://github.com/learn-co-curriculum/dsc-1-02-16-measures-of-dispersion-quiz/commit/64211652f9900d4bc4abaaa841cc45deda3b7105
