### ISSUE TITLE
Correct "Plot a histogram to verify your answers"

### ISSUE THREAD

**Issue by erdosn** [learn-co-curriculum/dsc-1-02-16-measures-of-dispersion-quiz#2]
On this quiz, it seems like this should read "Plot a boxplot to verify your answers"

**Comment by PeterBell** [comment]
Thanks for catching! Just fixed with https://github.com/learn-co-curriculum/dsc-1-02-16-measures-of-dispersion-quiz/commit/64211652f9900d4bc4abaaa841cc45deda3b7105
